Fix Android Termux: "ImportError: cannot import name 'SemLock' from '_multiprocessing'"
See #61.
Does notion-py actually use multiple processes?
If not maybe we can just switch to `threading.Lock`.